trigger:
- main  # Ensure this matches your branch name

pool:
  vmImage: 'ubuntu-latest'

variables:
  PYTHON_VERSION: '3.10'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(PYTHON_VERSION)'
    addToPath: true

- script: |
    python -m venv venv
    source venv/bin/activate
    pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install Dependencies'

- script: |
    echo "Starting Deployment to Azure"
  displayName: 'Pre-Deployment Steps'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '<YOUR_AZURE_SUBSCRIPTION>'
    appName: 'truth-lens-api'
    runtimeStack: 'PYTHON|3.10'
    package: '.'
    startUpCommand: 'gunicorn -w 4 -k uvicorn.workers.UvicornWorker app:app'

- script: |
    echo "Deployment Successful!"
  displayName: 'Post-Deployment Steps'

